//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrengthReport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrengthReport.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] dictionary_gzip {
            get {
                object obj = ResourceManager.GetObject("dictionary_gzip", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;LayoutBox xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Layout Name=&quot;Corporate&quot; Title=&quot;Corporate&quot;&gt;
        ///    &lt;ArrayOfLayoutElement&gt;
        ///      &lt;LayoutElement&gt;
        ///        &lt;Width&gt;25&lt;/Width&gt;
        ///        &lt;Data&gt;
        ///          &lt;StaticData&gt;Title&lt;/StaticData&gt;
        ///          &lt;FunctionType /&gt;
        ///        &lt;/Data&gt;
        ///        &lt;Filter&gt;
        ///          &lt;Comparator&gt;&amp;lt;=&lt;/Comparator&gt;
        ///          &lt;CompareWith&gt;Medium&lt;/CompareWith&gt;
        ///          &lt;Enabled&gt;false&lt;/E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LayoutsDefault {
            get {
                return ResourceManager.GetString("LayoutsDefault", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon StrengthReport {
            get {
                object obj = ResourceManager.GetObject("StrengthReport", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon StrengthReportPrinting {
            get {
                object obj = ResourceManager.GetObject("StrengthReportPrinting", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TemplateBox&gt;
        ///&lt;Template&gt;
        ///	&lt;Header&gt;
        ///		&lt;Font&gt;
        ///			&lt;FontName&gt;Arial&lt;/FontName&gt;
        ///			&lt;Embed&gt;true&lt;/Embed&gt;
        ///			&lt;Color C=&quot;255&quot; M=&quot;0&quot; Y=&quot;0&quot; K=&quot;0&quot;/&gt;
        ///			&lt;Size&gt;12&lt;/Size&gt;
        ///			&lt;Encoding&gt;winansi&lt;/Encoding&gt;
        ///			&lt;Source&gt;SYSTEM&lt;/Source&gt;
        ///        &lt;/Font&gt;
        ///		&lt;Alignment&gt;Center&lt;/Alignment&gt;
        ///		&lt;Background R=&quot;0&quot; G=&quot;0&quot; B=&quot;0&quot;/&gt;
        ///    &lt;/Header&gt;
        ///
        ///	&lt;Footer&gt;
        ///		&lt;Font&gt;
        ///			&lt;FontName&gt;Arial&lt;/FontName&gt;
        ///			&lt;Embed&gt;true&lt;/Embed&gt;
        ///			&lt;Color C=&quot;255&quot; M=&quot;0&quot; Y=&quot;0&quot; K=&quot;0&quot;/&gt;
        ///			&lt;Size&gt;12&lt;/Size&gt;
        ///			&lt;Encoding [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplatesDefault {
            get {
                return ResourceManager.GetString("TemplatesDefault", resourceCulture);
            }
        }
    }
}
