//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StrengthReportTest.Templating {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TemplatingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplatingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StrengthReportTest.Templating.TemplatingResources", typeof(TemplatingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;TemplateBox xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Template&gt;
        ///    &lt;Name&gt;Example Template&lt;/Name&gt;
        ///    &lt;PageSize&gt;
        ///      &lt;Width&gt;210&lt;/Width&gt;
        ///      &lt;Height&gt;297&lt;/Height&gt;
        ///    &lt;/PageSize&gt;
        ///    &lt;Margin&gt;
        ///      &lt;Top&gt;50&lt;/Top&gt;
        ///      &lt;Bottom&gt;20&lt;/Bottom&gt;
        ///      &lt;Left&gt;20&lt;/Left&gt;
        ///      &lt;Right&gt;20&lt;/Right&gt;
        ///    &lt;/Margin&gt;
        ///    &lt;ReportHeading&gt;
        ///      &lt;Font&gt;
        ///        &lt;Source&gt;SYSTEM&lt;/Source&gt;
        ///        &lt;FontName&gt;Arial&lt;/Font [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplatesDefault {
            get {
                return ResourceManager.GetString("TemplatesDefault", resourceCulture);
            }
        }
    }
}
