//------------------------------------------------------------------------------
// <auto-generated>
//     Ezt a kódot eszköz generálta.
//     Futásidejű verzió:2.0.50727.3074
//
//     Ennek a fájlnak a módosítása helytelen viselkedést eredményezhet, és elvész, ha
//     a kódot újragenerálják.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace StrengthReport.Templating {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Template {
        
        private string nameField;
        
        private Size pageSizeField;
        
        private Margin marginField;
        
        private Style reportHeaderField;
        
        private Style reportFooterField;
        
        private Style headerField;
        
        private Style groupHeadingField;
        
        private Style rowField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public Size PageSize {
            get {
                return this.pageSizeField;
            }
            set {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        public Margin Margin {
            get {
                return this.marginField;
            }
            set {
                this.marginField = value;
            }
        }
        
        /// <remarks/>
        public Style ReportHeader {
            get {
                return this.reportHeaderField;
            }
            set {
                this.reportHeaderField = value;
            }
        }
        
        /// <remarks/>
        public Style ReportFooter {
            get {
                return this.reportFooterField;
            }
            set {
                this.reportFooterField = value;
            }
        }
        
        /// <remarks/>
        public Style Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public Style GroupHeading {
            get {
                return this.groupHeadingField;
            }
            set {
                this.groupHeadingField = value;
            }
        }
        
        /// <remarks/>
        public Style Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Size {
        
        private float widthField;
        
        private float heightField;
        
        /// <remarks/>
        public float Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public float Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Color {
        
        private byte cField;
        
        private byte mField;
        
        private byte yField;
        
        private byte kField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte C {
            get {
                return this.cField;
            }
            set {
                this.cField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte M {
            get {
                return this.mField;
            }
            set {
                this.mField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Font {
        
        private FontSource sourceField;
        
        private string fontNameField;
        
        private FontFontStyle fontStyleField;
        
        private Color colorField;
        
        private float sizeField;
        
        private bool embedField;
        
        private string encodingField;
        
        public Font() {
            this.encodingField = "default";
        }
        
        /// <remarks/>
        public FontSource Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string FontName {
            get {
                return this.fontNameField;
            }
            set {
                this.fontNameField = value;
            }
        }
        
        /// <remarks/>
        public FontFontStyle FontStyle {
            get {
                return this.fontStyleField;
            }
            set {
                this.fontStyleField = value;
            }
        }
        
        /// <remarks/>
        public Color Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public float Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public bool Embed {
            get {
                return this.embedField;
            }
            set {
                this.embedField = value;
            }
        }
        
        /// <remarks/>
        public string Encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum FontSource {
        
        /// <remarks/>
        SYSTEM,
        
        /// <remarks/>
        FILE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum FontFontStyle {
        
        /// <remarks/>
        Normal,
        
        /// <remarks/>
        Bold,
        
        /// <remarks/>
        Italic,
        
        /// <remarks/>
        BoldItalic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Style {
        
        private Font fontField;
        
        private StyleAlignment alignmentField;
        
        private StyleBackgrounds backgroundsField;
        
        private float heightField;
        
        /// <remarks/>
        public Font Font {
            get {
                return this.fontField;
            }
            set {
                this.fontField = value;
            }
        }
        
        /// <remarks/>
        public StyleAlignment Alignment {
            get {
                return this.alignmentField;
            }
            set {
                this.alignmentField = value;
            }
        }
        
        /// <remarks/>
        public StyleBackgrounds Backgrounds {
            get {
                return this.backgroundsField;
            }
            set {
                this.backgroundsField = value;
            }
        }
        
        /// <remarks/>
        public float Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public enum StyleAlignment {
        
        /// <remarks/>
        Left,
        
        /// <remarks/>
        Right,
        
        /// <remarks/>
        Center,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class StyleBackgrounds {
        
        private Color[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Background")]
        public Color[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Margin {
        
        private float topField;
        
        private float bottomField;
        
        private float leftField;
        
        private float rightField;
        
        /// <remarks/>
        public float Top {
            get {
                return this.topField;
            }
            set {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        public float Bottom {
            get {
                return this.bottomField;
            }
            set {
                this.bottomField = value;
            }
        }
        
        /// <remarks/>
        public float Left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        public float Right {
            get {
                return this.rightField;
            }
            set {
                this.rightField = value;
            }
        }
    }
}
