using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using KeePass.UI;

namespace StrengthReport.Reporting.ReportFormat {
    public partial class ReportScreenForm : Form {
        private DataTable m_DataTable;

        string w_Title = "Report";
        string w_Desc  = "Generated by StrengthReport";
        Icon   w_Icon  = new Icon(Resources.StrengthReport, 48, 48);

        public ReportScreenForm(string title, DataTable dataTable) {
            if (title != null && title.Length > 0) {
                w_Title = title + " (Report)";
            }

            w_Desc = "Generated by StrengthReport at  @ " + DateTime.Now.ToString();
            m_DataTable = dataTable;
            InitializeComponent();
            
        }

        private void ReportScreenForm_Load(object sender, EventArgs e) {
            doHeader();

            dataGridView.DataSource = m_DataTable;

        }

        private void panel1_Paint(object sender, PaintEventArgs e) {

        }

        private void doHeader() {
            this.Text = w_Title;
            m_bannerImage.Image = BannerFactory.CreateBanner(m_bannerImage.Width,
                m_bannerImage.Height, BannerStyle.Default,
                w_Icon.ToBitmap(), w_Title, w_Desc);
        }

        private void panel1_SizeChanged(object sender, EventArgs e) {
            doHeader();
        }

        private void btnPdf_Click(object sender, EventArgs e) {

        }

        private void btnClose_Click(object sender, EventArgs e) {
            this.Close();
        }

        
    }
}
